---
- hosts: miners
  become: true
  vars:
    xmr_stak_donate: true
    xmr_stak_donate_amount: 0.25
    update_xmr_stak: false
    monit_cycle: 300
    monit_services:
      - name: xmr-stak
        type: process_by_name
        target: xmr-stak
        start: /usr/local/bin/start-mining monero
        stop: /usr/local/bin/stop-mining
        user: skibler
        group: skibler
      - name: xmr-stak-prometheus-exporter
        type: process_by_name
        target: xmr-stak-prometheus-exporter
        start: "/bin/sh -c '/usr/local/bin/xmr-stak-prometheus-exporter &'"
        stop: /usr/bin/killall xmr-stak-prometheus-exporter
        user: root
        group: root
    xmr_stak_currencies:
      - monero
    xmr_stak_configs:
      monero:
        pool: "{{ xmrstak_vault.monero.pool }}"
        wallet: "{{ xmrstak_vault.monero.wallet }}"
        password: "{{ xmrstak_vault.monero.password }}"
  tasks:
    - user:
      args:
        name: skibler
        append: yes
        groups: ["sudo", "video", "adm"]

    - authorized_key:
      args:
        user: skibler
        key: https://github.com/seankibler.keys

    - name: Passwordless sudo
      lineinfile:
        path: /etc/sudoers
        backup: yes
        line: "%sudo   ALL=(ALL) NOPASSWD:ALL"

    - name: Checkout amdmeminfo
      git:
        repo: https://github.com/ystarnaud/amdmeminfo
        dest: /usr/local/src/amdmeminfo
        update: no

    - name: Compile amdmeminfo
      make:
        chdir: /usr/local/src/amdmeminfo

    - name: Install amdmeminfo
      copy:
        dest: /usr/local/bin/amdmeminfo
        src: /usr/local/src/amdmeminfo/amdmeminfo
        force: yes
        mode: 0755
        owner: root
        group: root
        remote_src: True

    # - name: Install xmrstak prometheus exporter
    #   get_url:
    #     url: https://github.com/seankibler/xmr-stak-prometheus-exporter/releases/download/v1.0.0/xmr-stak-prometheus-exporter
    #     dest: /usr/local/bin/xmr-stak-prometheus-exporter
    #     owner: root
    #     group: root
    #     mode: 0755
    #     checksum: sha256:d64fa8bfe372256bb635060e09b1d2c78f0c961bb08a20ba50e4a508955806ad

    - name: Install scripts
      copy:
        src: files/
        dest: /usr/local/bin/
        mode: 0755
        owner: root
        group: root

    # - name: Fanspeed control cron
    #   cron:
    #     name: "fanspeed control"
    #     job: "/usr/local/bin/amdfancontrol"
    #     minute: "*/5"

  roles:
    # - seankibler.amdgpu-pro
    - xmr-stak
    # - pgolm.monit
