---
- hosts: miners
  become: true
  vars:
    xmr_stak_donate: true
    update_xmr_stak: false
    monit_cycle: 300
    monit_services:
      - name: xmr-stak
        type: process_by_name
        target: xmr-stak
        start: /usr/local/bin/mine monero
        stop: /usr/local/bin/stop-mining
        user: skibler
        group: skibler
    xmr_stak_currencies:
      - monero
    xmr_stak_configs:
      monero:
        pool: "{{ xmrstak_vault.monero.pool }}"
        wallet: "{{ xmrstak_vault.monero.wallet }}"
        password: "{{ xmrstak_vault.monero.password }}"
  roles:
    # - seankibler.amdgpu-pro
    - xmr-stak
    - pgolm.monit
