---
# tasks file for xmr-stak

- name: Nvidia Repo Installer
  apt:
    deb: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.1.85-1_amd64.deb

- name: Nvidia Repo Key
  apt_key:
    url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub

- name: Install dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes

- name: Download
  git:
    dest: /usr/local/src/xmr-stak
    repo: https://github.com/fireice-uk/xmr-stak.git
    update: no

- name: Adjust donation
  replace:
    path: /usr/local/src/xmr-stak/xmrstak/donate-level.hpp
    regexp: "2.0 / 100.0"
    replace: "0.0"

- name: Create build dir
  file: state=directory path=/usr/local/src/xmr-stak/build

- name: Compile
  shell: "cmake {{ cmake_args }} ../ && make install"
  args:
    creates: "/usr/local/src/xmr-stak/build/install_manifest.txt"
    chdir: /usr/local/src/xmr-stak/build
  notify:
    - cleanup xmr-stak install

- name: Install control scripts
  copy:
    src: files/bin/
    dest: /usr/local/bin
    owner: root
    group: adm

- name: Create config dirs
  file:
    state: directory
    path: "/usr/local/etc/xmr-stak/{{ item }}"
    owner: root
    group: adm
    mode: 0770
  with_items: "{{ currencies }}"

- name: Install configs
  template:
    src: "files/configs/{{ item }}/config.txt.j2"
    dest: "/usr/local/etc/xmr-stak/{{ item }}/config.txt"
    owner: root
    group: adm
    mode: 0640
  with_items: "{{ currencies }}"
  tags:
    - xmr-stak-config

- name: Create logs dir
  file:
    path: "{{ log_dir }}"
    state: directory
    owner: root
    group: adm
    mode: 0770

- name: Reduce swappiness
  sysctl:
    name: vm.swappiness
    value: 5
    state: present
    reload: yes

- name: Set hugepages
  sysctl:
    name: vm.nr_hugepages
    value: 128
    state: present
    reload: yes

- name: Set ulimits
  copy:
    src: files/limits.conf
    dest: /etc/security/limits.conf
    backup: yes

- name: Miner Cron
  cron:
    name: xmr-stak miner
    minute: "*/15"
    job: "/usr/local/bin/start-mining aeon"
