#!/usr/bin/env bash

FANSPEED_MIN=45
GPUS="0 1 2 3 4"

for GPU in $GPUS; do
  current_speed=$(/usr/bin/env ohgodatool -i $GPU --show-fanspeed | tr -d '%')

  if [ $? -ne 0 ]; then
    continue
  fi

  if [ $current_speed -lt $FANSPEED_MIN ]; then
    /usr/bin/env ohgodatool -i $GPU --set-fanspeed $FANSPEED_MIN
  fi
done
