#! /usr/bin/env bash

CARD0_CORE_OC=1150
CARD0_MEM_OC=1800
CARD0_CORE_V_IDX=5
CARD0_FANSPEED=40
CARD1_CORE_OC=1150
CARD1_MEM_OC=1850
CARD1_CORE_V_IDX=5
CARD1_FANSPEED=40

ohgodatool -i 0 --set-fanspeed $CARD0_FANSPEED \
  && ohgodatool -i 0 --core-state 7 --core-vddc-idx $CARD0_CORE_V_IDX \
  && ohgodatool -i 0 --core-state 7 --core-clock $CARD0_CORE_OC \
  && ohgodatool -i 0 --mem-state 2 --mem-clock $CARD0_MEM_OC

ohgodatool -i 2 --set-fanspeed $CARD1_FANSPEED \
  && ohgodatool -i 2 --core-state 7 --core-vddc-idx $CARD1_CORE_V_IDX \
  && ohgodatool -i 2 --core-state 7 --core-clock $CARD1_CORE_OC \
  && ohgodatool -i 2 --mem-state 2 --mem-clock $CARD1_MEM_OC
