#! /bin/bash

set -uo pipefail

if [ $# -lt 1 ]; then
  echo <<EOUSAGE
$0 start <coin>
$0 stop
EOUSAGE
  exit 1
fi

ACTION=$1

function start_miner() {
  COIN=$1
  CONF_DIR=/usr/local/etc/xmr-stak/$COIN
  LOG=/var/log/xmr-stak/${COIN}.log

  if [ ! -f $CONF_DIR/amd.txt -o ! -f $CONF_DIR/pools.txt -o ! -f $CONF_DIR/config.txt ]; then
    echo "Missing config files for coin \"$COIN\" in $CONF_DIR"
    exit 1
  fi

  ps -C xmr-stak > /dev/null

  if [ $? -ne 0 ]; then
    echo "Begin mining: \"$COIN\""

    cd /usr/local/bin && exec xmr-stak --noCPU \
      --amd $CONF_DIR/amd.txt \
      -c $CONF_DIR/config.txt \
      -C $CONF_DIR/pools.txt \
      -i 10000 >> $LOG
  else
    echo "Miner already running." 1>&2
    exit 1
  fi
}

function stop_miner() {
  echo "Stop mining..."
  ps aux | grep xmr-stak | grep -v grep > /dev/null

  if [ $? -eq 0 ]; then
    killall xmr-stak
    exit 0
  else
    echo "Miner is not running..." 1>&2
    exit 1
  fi
}

case $ACTION in
  start)
    start_miner $2
    ;;
  stop)
    stop_miner
    ;;
  *)
    echo "Invalid action \"$ACTION\"" 1>&2 ;;
esac
