---
# tasks file for common

- name: Common packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  tags:
    - apt
    - packages

- name: Configure sensors
  command: "sensors-detect --auto"
  args:
    creates: /etc/sensors3.conf

- name: Nginx php-fpm default config
  copy:
    backup: yes
    dest: /etc/nginx/sites-available/default
    src: files/nginx/default
  notify:
    - restart nginx

- name: Miner web monitor files
  copy:
    dest: /var/www/html
    src: files/html/
  tags:
    - web

- name: Tmux config
  copy:
    src: files/.tmux.conf
    dest: /home/skibler/.tmux.conf
